name: Extract ZIP and Commit Contents

on:
  push:
    
jobs:
  extract-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user identity
        run: |
          git config --global user.email "alt444.001@gmail.com"
          git config --global user.name "jay_"

      - name: Unzip the file without overwriting existing files
        run: |
          # Find all zip files and extract their contents directly into the root directory
          for zip_file in $(find . -name '*.zip'); do
            # Unzip only the new or modified files (no overwrite)
            unzip -n "$zip_file" -d .  # Extract directly into the root of the repo
          done

      - name: Check for changes and commit
        run: |
          git add .
          git diff --cached --exit-code || git commit -m "Add or update extracted files from ZIP"

      - name: Push changes
        run: |
          git push origin main  # Push to the main branch (adjust if necessary)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically set by GitHub
